language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm start
deploy:
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./node_modules/.bin/
  on:
    branch: master